export const mockJourney = [
  { type: "Onboard", sub: "login", contained: true },
  { type: "Onboard", sub: "license" },
  {
    type: "Inspection",
    sub: "pre",
    step: "front",
    overlayImage: "FrontFull.png",
    overlayImageSize: "50%",
    side: "FRONT_SIDE",
  },
  {
    type: "Inspection",
    sub: "pre",
    step: "passengerside",
    overlayImage: "PassengerSideFull.png",
    overlayImageSize: "60%",
    overlayImagePosition: "40%",
    side: "PASSENGER_SIDE",
  },
  {
    type: "Inspection",
    sub: "pre",
    step: "rear",
    overlayImage: "RearFull.png",
    overlayImageSize: "50%",
    side: "REAR_SIDE",
  },
  {
    type: "Inspection",
    sub: "pre",
    step: "driverside",
    overlayImage: "DriverSideFull.png",
    overlayImageSize: "60%",
    overlayImagePosition: "40%",
    side: "DRIVER_SIDE",
  },
  {
    type: "Offboard",
    sub: "Odometer",
    overlayImage: "DriverSideFull.png",
    overlayImageSize: "60%",
    overlayImagePosition: "40%",
    side: "ODOMETER",
  },
  { type: "Summary", sub: "report" },
];
