export const quoteJourney = [
  { type: "Onboard", sub: "accesscode", contained: true },
  { type: "Onboard", sub: "termsofuse", contained: true },
  { type: "Onboard", sub: "login", contained: true },
  { type: "Onboard", sub: "inspectiontype", contained: true },
  { type: "Onboard", sub: "license" },
  { type: "Onboard", sub: "Damageparts" },
  { type: "Inspection", sub: "Claim" },
  {
    type: "Offboard",
    sub: "Odometer",
    overlayImage: "DriverSideFull.png",
    overlayImageSize: "60%",
    overlayImagePosition: "40%",
    side: "ODOMETER",
  },
  { type: "Summary", sub: "report" },
  //   "reference data",
  {
    type: "Inspection",
    sub: "claim",
    step: "exterior-bonnet",
    overlayImage: "front_side/bonnet.png",
    overlayImageSize: "80%",
    overlayImagePosition: "11%",
    side: "FRONT_BONNET",
    label: "Front Bonnet",
    area: "FRONT",
    subArea: "BONNET"
  },
  // "frontrightheadlight",
  {
    type: "Inspection",
    sub: "claim",
    step: "exterior-frontrightheadlight",
    overlayImage: "front_side/Headlight_PassengerSide.png",
    overlayImageSize: "50%",
    side: "FRONT_PASSENGER_SIDE_HEAD_LIGHT",
    label: "Front Passenger Side Head Light",
    area: "FRONT",
    subArea: "PASSENGER_SIDE_HEAD_LIGHT"
  },
  // "frontrightbumper",
  {
    type: "Inspection",
    sub: "claim",
    step: "exterior-frontrightbumper",
    overlayImage: "front_side/Bumper_PassengerSide.png",
    overlayImageSize: "50%",
    side: "FRONT_PASSENGER_SIDE_BUMPER",
    label: "Front Passenger Side Bumper",
    area:"FRONT",
    subArea:"PASSENGER_SIDE_BUMPER"
  },
  // "frontleftheadlight",
  {
    type: "Inspection",
    sub: "claim",
    step: "exterior-frontleftheadlight",
    overlayImage: "front_side/Headlight_DriverSide.png",
    overlayImageSize: "50%",
    side: "FRONT_DRIVER_SIDE_HEAD_LIGHT",
    label: "Front Driver Side Head Light",
    area: "FRONT",
    subArea: "DRIVER_SIDE_HEAD_LIGHT",
  },
  // "frontleftbumper",
  {
    type: "Inspection",
    sub: "claim",
    step: "exterior-frontleftbumper",
    overlayImage: "front_side/Bumper_DriverSide.png",
    overlayImageSize: "50%",
    side: "FRONT_DRIVER_SIDE_BUMPER",
    label: "Front Driver Side Bumper",
    area: "FRONT",
    subArea: "DRIVER_SIDE_BUMPER",
  },
  // "passengersidefrontrim",
  {
    type: "Inspection",
    sub: "claim",
    step: "exterior-passengersidefrontrim",
    overlayImage: "passenger_side/Front-Wheel.png",
    overlayImageSize: "50%",
    side: "PASSENGER_SIDE_FRONT_RIM",
    label: "Passenger Side Front Rim",
    area: "PASSENGER_SIDE",
    subArea: "FRONT_RIM",
  },
  // "passengersidefronttyre",
  {
    type: "Inspection",
    sub: "claim",
    step: "exterior-passengersidefronttyre",
    overlayImage: "passenger_side/Front-Wheel.png",
    overlayImageSize: "50%",
    side: "PASSENGER_SIDE_FRONT_WHEEL",
    label: "Passenger Side Front Wheel",
    area: "PASSENGER_SIDE",
    subArea: "FRONT_WHEEL",
  },
  // "passengersidefender",
  {
    type: "Inspection",
    sub: "claim",
    step: "exterior-passengersidefender",
    overlayImage: "passenger_side/Fender.png",
    overlayImageSize: "50%",
    side: "PASSENGER_SIDE_FENDER",
    label: "Passenger Side Fender",
    area: "PASSENGER_SIDE",
    subArea: "FENDER",
  },
  // "passengersidefrontdoor",
  {
    type: "Inspection",
    sub: "claim",
    step: "exterior-passengersidefrontdoor",
    overlayImage: "passenger_side/FrontDoor.png",
    overlayImageSize: "50%",
    side: "PASSENGER_SIDE_FRONT_DOOR",
    label: "Passenger Side Front Door",
    area: "PASSENGER_SIDE",
    subArea: "FRONT_DOOR",
  },
  // "passengersidereardoor",
  {
    type: "Inspection",
    sub: "claim",
    step: "exterior-passengersidereardoor",
    overlayImage: "passenger_side/RearDoor.png",
    overlayImageSize: "50%",
    side: "PASSENGER_SIDE_REAR_DOOR",
    label: "Passenger Side Rear Door",
    area: "PASSENGER_SIDE",
    subArea: "REAR_DOOR",
  },
  // "passengersiderockerpanel",
  {
    type: "Inspection",
    sub: "claim",
    step: "exterior-passengersiderockerpanel",
    overlayImage: "passenger_side/RocketPanel.png",
    overlayImageSize: "50%",
    side: "PASSENGER_SIDE_ROCKER_PANEL",
    label: "Passenger Side Rocker Panel",
    area: "PASSENGER_SIDE",
    subArea: "ROCKER_PANEL",
  },
  // "passengersidequarter",
  {
    type: "Inspection",
    sub: "claim",
    step: "exterior-passengersidequarter",
    overlayImage: "passenger_side/Quarter.png",
    overlayImageSize: "50%",
    side: "PASSENGER_SIDE_QUATER",
    label: "Passenger Side Quarter",
    area: "PASSENGER_SIDE",
    subArea: "QUATER",
  },
  // "passengersidereartyre",
  {
    type: "Inspection",
    sub: "claim",
    step: "exterior-passengersidereartyre",
    overlayImage: "passenger_side/RearWheel.png",
    overlayImageSize: "50%",
    side: "PASSENGER_SIDE_REAR_WHEEL",
    label: "Passenger Side Rear WHEEL",
    area: "PASSENGER_SIDE",
    subArea: "REAR_WHEEL",
  },
  // "passengersiderearrim",
  {
    type: "Inspection",
    sub: "claim",
    step: "exterior-passengersiderearrim",
    overlayImage: "passenger_side/RearWheel.png",
    overlayImageSize: "50%",
    side: "PASSENGER_SIDE_REAR_RIM",
    label: "Passenger Side Rear Rim",
    area: "PASSENGER_SIDE",
    subArea: "REAR_RIM",
  },
  // "driversiderearrim",
  {
    type: "Inspection",
    sub: "claim",
    step: "exterior-driversiderearrim",
    overlayImage: "passenger_side/RearWheel.png",
    overlayImageSize: "50%",
    side: "DRIVER_SIDE_REAR_RIM",
    label: "Driver Side Rear Rim",
    area: "DRIVER_SIDE",
    subArea: "REAR_RIM",
  },
  // "driversidereartyre",
  {
    type: "Inspection",
    sub: "claim",
    step: "exterior-driversidereartyre",
    overlayImage: "driver_side/RearWheel.png",
    overlayImageSize: "50%",
    side: "DRIVER_SIDE_REAR_WHEEL",
    label: "Driver Side Rear Wheel",
    area: "DRIVER_SIDE",
    subArea: "REAR_WHEEL",
  },
  // "driversidequarter",
  {
    type: "Inspection",
    sub: "claim",
    step: "exterior-driversidequarter",
    overlayImage: "driver_side/Quarter.png",
    overlayImageSize: "50%",
    side: "DRIVER_SIDE_QUATER",
    label: "Driver Side Quarter",
    area: "DRIVER_SIDE",
    subArea: "QUATER",
  },
  // "driversidereardoor",
  {
    type: "Inspection",
    sub: "claim",
    step: "exterior-driversidereardoor",
    overlayImage: "driver_side/RearDoor.png",
    overlayImageSize: "50%",
    side: "DRIVER_SIDE_REAR_DOOR",
    label: "Driver Side Rear Door",
    area: "DRIVER_SIDE",
    subArea: "REAR_DOOR",
  },
  // "driversidefrontdoor",
  {
    type: "Inspection",
    sub: "claim",
    step: "exterior-driversidefrontdoor",
    overlayImage: "driver_side/FrontDoor.png",
    overlayImageSize: "50%",
    side: "DRIVER_SIDE_FRONT_DOOR",
    label: "Driver Side Front Door",
    area: "DRIVER_SIDE",
    subArea: "FRONT_DOOR",
  },
  // "driversiderockerpanel",
  {
    type: "Inspection",
    sub: "claim",
    step: "exterior-driversiderockerpanel",
    overlayImage: "driver_side/RockerPanel.png",
    overlayImageSize: "50%",
    side: "DRIVER_SIDE_ROCKER_PANEL",
    label: "Driver Side Rocker Panel",
    area: "DRIVER_SIDE",
    subArea: "ROCKER_PANEL",
  },
  // "driversidefender",
  {
    type: "Inspection",
    sub: "claim",
    step: "exterior-driversidefender",
    overlayImage: "driver_side/Fender.png",
    overlayImageSize: "50%",
    side: "DRIVER_SIDE_FENDER",
    label: "Driver Side Fender",
    area: "DRIVER_SIDE",
    subArea: "FENDER",
  },
  // "driversidefronttyre",
  {
    type: "Inspection",
    sub: "claim",
    step: "exterior-driversidefronttyre",
    overlayImage: "driver_side/FrontFull.png",
    overlayImageSize: "50%",
    side: "DRIVER_SIDE_FRONT_WHEEL",
    label: "Driver Side Front WHEEL",
    area: "DRIVER_SIDE",
    subArea: "FRONT_WHEEL",
  },
  // "driversidefrontrim",
  {
    type: "Inspection",
    sub: "claim",
    step: "exterior-driversidefrontrim",
    overlayImage: "driver_side/FrontFull.png",
    overlayImageSize: "50%",
    side: "DRIVER_SIDE_FRONT_RIM",
    label: "Driver Side Front Rim",
    area: "DRIVER_SIDE",
    subArea: "FRONT_RIM",
  },
  // "windshield",
  {
    type: "Inspection",
    sub: "claim",
    step: "exterior-windshield",
    overlayImage: "glass_and_wheels/FrontFull.png",
    overlayImageSize: "50%",
    side: "WIND_SCREEN",
    label: "Front Wind Screen",
    area: "FRONT",
    subArea: "WIND_SCREEN",
  },
  // "top",
  {
    type: "Inspection",
    sub: "claim",
    step: "exterior-top",
    overlayImage: "FrontFull.png",
    overlayImageSize: "50%",
    side: "TOP",
    label: "Top",
    area: "FRONT",
    subArea: "TOP",
  },
  // "rearrightheadlight",
  {
    type: "Inspection",
    sub: "claim",
    step: "exterior-rearrightheadlight",
    overlayImage: "FrontFull.png",
    overlayImageSize: "50%",
    side: "FRONT_PASSENGER_SIDE_HEAD_LIGHT",
    label: "Front Passenger Side Head Light",
    area: "FRONT",
    subArea: "PASSENGER_SIDE_HEAD_LIGHT",
  },
  // "rearrightbumper",
  {
    type: "Inspection",
    sub: "claim",
    step: "exterior-rearrightbumper",
    overlayImage: "FrontFull.png",
    overlayImageSize: "50%",
    side: "FRONT_PASSENGER_SIDE_BUMPER",
    label: "Front Passenger Side Bumper",
    area: "FRONT",
    subArea: "PASSENGER_SIDE_BUMPER",
  },
  // "rearleftheadlight",
  {
    type: "Inspection",
    sub: "claim",
    step: "exterior-rearleftheadlight",
    overlayImage: "FrontFull.png",
    overlayImageSize: "50%",
    side: "FRONT_DRIVER_SIDE_HEAD_LIGHT",
    label: "Front Driver Side Head Light",
    area: "FRONT",
    subArea: "DRIVER_SIDE_HEAD_LIGHT",
  },
  // "rearleftbumper",
  {
    type: "Inspection",
    sub: "claim",
    step: "exterior-rearleftbumper",
    overlayImage: "FrontFull.png",
    overlayImageSize: "50%",
    side: "REAR_DRIVER_SIDE_BUMPER",
    label: "Rear Driver Side Bumper",
    area: "REAR",
    subArea: "DRIVER_SIDE_BUMPER",
  },
  // "boot",
  {
    type: "Inspection",
    sub: "claim",
    step: "exterior-boot",
    overlayImage: "FrontFull.png",
    overlayImageSize: "50%",
    side: "REAR_BOOT",
    label: "Rear Boot",
    area: "REAR",
    subArea: "BOOT",
  },
  // "rearscreen"
  {
    type: "Inspection",
    sub: "claim",
    step: "exterior-rearscreen",
    overlayImage: "FrontFull.png",
    overlayImageSize: "50%",
    side: "REAR_WIND_SCREEN",
    label: "Rear Screen",
    area: "REAR",
    subArea: "WIND_SCREEN",
  },
];
