export const quoteJourney = [
  { type: "Onboard", sub: "accesscode", contained: true },
  { type: "Onboard", sub: "termsofuse", contained: true },
  { type: "Onboard", sub: "login", contained: true },
  { type: "Onboard", sub: "inspectiontype", contained: true },
  { type: "Onboard", sub: "license" },
  { type: "Onboard", sub: "Damageparts" },
  { type: "Inspection", sub: "Claim" },
  {
    type: "Offboard",
    sub: "Odometer",
    overlayImage: "DriverSideFull.png",
    overlayImageSize: "60%",
    overlayImagePosition: "40%",
    side: "ODOMETER",
  },
  { type: "Summary", sub: "report" },
  //   "reference data",
  {
    type: "Inspection",
    sub: "claim",
    step: "exterior-bonnet",
    overlayImage: "FrontFull.png",
    overlayImageSize: "50%",
    side: "BONNET",
  },
  // "frontrightheadlight",
  {
    type: "Inspection",
    sub: "claim",
    step: "exterior-frontrightheadlight",
    overlayImage: "FrontFull.png",
    overlayImageSize: "50%",
    side: "FRONT_RIGHT_HEADLIGHT",
  },
  // "frontrightbumper",
  {
    type: "Inspection",
    sub: "claim",
    step: "exterior-frontrightbumper",
    overlayImage: "FrontFull.png",
    overlayImageSize: "50%",
    side: "FRONT_RIGHT_BUMPER",
  },
  // "frontleftheadlight",
  {
    type: "Inspection",
    sub: "claim",
    step: "exterior-frontleftheadlight",
    overlayImage: "FrontFull.png",
    overlayImageSize: "50%",
    side: "FRONT_LEFT_HEADLIGHT",
  },
  // "frontleftbumper",
  {
    type: "Inspection",
    sub: "claim",
    step: "exterior-frontleftbumper",
    overlayImage: "FrontFull.png",
    overlayImageSize: "50%",
    side: "FRONT_LEFT_BUMPER",
  },
  // "passengersidefrontrim",
  {
    type: "Inspection",
    sub: "claim",
    step: "exterior-passengersidefrontrim",
    overlayImage: "FrontFull.png",
    overlayImageSize: "50%",
    side: "PASSENGER_SIDE_FRONT_RIM",
  },
  // "passengersidefronttyre",
  {
    type: "Inspection",
    sub: "claim",
    step: "exterior-passengersidefronttyre",
    overlayImage: "FrontFull.png",
    overlayImageSize: "50%",
    side: "PASSENGER_SIDE_FRONT_TYPE",
  },
  // "passengersidefender",
  {
    type: "Inspection",
    sub: "claim",
    step: "exterior-passengersidefender",
    overlayImage: "FrontFull.png",
    overlayImageSize: "50%",
    side: "PASSENGER_SIDE_FENDER",
  },
  // "passengersidefrontdoor",
  {
    type: "Inspection",
    sub: "claim",
    step: "exterior-passengersidefrontdoor",
    overlayImage: "FrontFull.png",
    overlayImageSize: "50%",
    side: "PASSENGER_SIDE_FRONT_DOOR",
  },
  // "passengersidereardoor",
  {
    type: "Inspection",
    sub: "claim",
    step: "exterior-passengersidereardoor",
    overlayImage: "FrontFull.png",
    overlayImageSize: "50%",
    side: "PASSENGER_SIDE_REAR_DOOR",
  },
  // "passengersiderockerpanel",
  {
    type: "Inspection",
    sub: "claim",
    step: "exterior-passengersiderockerpanel",
    overlayImage: "FrontFull.png",
    overlayImageSize: "50%",
    side: "PASSENGER_SIDE_ROCKER_PANEL",
  },
  // "passengersidequarter",
  {
    type: "Inspection",
    sub: "claim",
    step: "exterior-passengersidequarter",
    overlayImage: "FrontFull.png",
    overlayImageSize: "50%",
    side: "PASSENGER_SIDE_QUARTER",
  },
  // "passengersidereartyre",
  {
    type: "Inspection",
    sub: "claim",
    step: "exterior-passengersidereartyre",
    overlayImage: "FrontFull.png",
    overlayImageSize: "50%",
    side: "PASSENGER_SIDE_REAR_TYRE",
  },
  // "passengersiderearrim",
  {
    type: "Inspection",
    sub: "claim",
    step: "exterior-passengersiderearrim",
    overlayImage: "FrontFull.png",
    overlayImageSize: "50%",
    side: "PASSENGER_SIDE_REAR_RIM",
  },
  // "driversiderearrim",
  {
    type: "Inspection",
    sub: "claim",
    step: "exterior-driversiderearrim",
    overlayImage: "FrontFull.png",
    overlayImageSize: "50%",
    side: "DRIVER_SIDE_REAR_RIM",
  },
  // "driversidereartyre",
  {
    type: "Inspection",
    sub: "claim",
    step: "exterior-driversidereartyre",
    overlayImage: "FrontFull.png",
    overlayImageSize: "50%",
    side: "DRIVER_SIDE_REAR_TYRE",
  },
  // "driversidequarter",
  {
    type: "Inspection",
    sub: "claim",
    step: "exterior-driversidequarter",
    overlayImage: "FrontFull.png",
    overlayImageSize: "50%",
    side: "DRIVER_SIDE_QUARTER",
  },
  // "driversidereardoor",
  {
    type: "Inspection",
    sub: "claim",
    step: "exterior-driversidereardoor",
    overlayImage: "FrontFull.png",
    overlayImageSize: "50%",
    side: "DRIVER_SIDE_REAR_DOOR",
  },
  // "driversidefrontdoor",
  {
    type: "Inspection",
    sub: "claim",
    step: "exterior-driversidefrontdoor",
    overlayImage: "FrontFull.png",
    overlayImageSize: "50%",
    side: "DRIVER_SIDE_FRONT_DOOR",
  },
  // "driversiderockerpanel",
  {
    type: "Inspection",
    sub: "claim",
    step: "exterior-driversiderockerpanel",
    overlayImage: "FrontFull.png",
    overlayImageSize: "50%",
    side: "DRIVER_SIDE_ROCKER_PANEL",
  },
  // "driversidefender",
  {
    type: "Inspection",
    sub: "claim",
    step: "exterior-driversidefender",
    overlayImage: "FrontFull.png",
    overlayImageSize: "50%",
    side: "DRIVER_SIDE_FENDER",
  },
  // "driversidefronttyre",
  {
    type: "Inspection",
    sub: "claim",
    step: "exterior-driversidefronttyre",
    overlayImage: "FrontFull.png",
    overlayImageSize: "50%",
    side: "DRIVER_SIDE_FRONT_TYRE",
  },
  // "driversidefrontrim",
  {
    type: "Inspection",
    sub: "claim",
    step: "exterior-driversidefrontrim",
    overlayImage: "FrontFull.png",
    overlayImageSize: "50%",
    side: "DRIVER_SIDE_FRONT_RIM",
  },
  // "windshield",
  {
    type: "Inspection",
    sub: "claim",
    step: "exterior-windshield",
    overlayImage: "FrontFull.png",
    overlayImageSize: "50%",
    side: "WINDSHIELD",
  },
  // "top",
  {
    type: "Inspection",
    sub: "claim",
    step: "exterior-top",
    overlayImage: "FrontFull.png",
    overlayImageSize: "50%",
    side: "TOP",
  },
  // "rearrightheadlight",
  {
    type: "Inspection",
    sub: "claim",
    step: "exterior-rearrightheadlight",
    overlayImage: "FrontFull.png",
    overlayImageSize: "50%",
    side: "FRONT_RIGHT_HEADLIGHT",
  },
  // "rearrightbumper",
  {
    type: "Inspection",
    sub: "claim",
    step: "exterior-rearrightbumper",
    overlayImage: "FrontFull.png",
    overlayImageSize: "50%",
    side: "FRONT_RIGHT_BUMPER",
  },
  // "rearleftheadlight",
  {
    type: "Inspection",
    sub: "claim",
    step: "exterior-rearleftheadlight",
    overlayImage: "FrontFull.png",
    overlayImageSize: "50%",
    side: "FRONT_LEFT_HEADLIGHT",
  },
  // "rearleftbumper",
  {
    type: "Inspection",
    sub: "claim",
    step: "exterior-rearleftbumper",
    overlayImage: "FrontFull.png",
    overlayImageSize: "50%",
    side: "REAR_LEFT_BUMPER",
  },
  // "boot",
  {
    type: "Inspection",
    sub: "claim",
    step: "exterior-boot",
    overlayImage: "FrontFull.png",
    overlayImageSize: "50%",
    side: "BOOT",
  },
  // "rearscreen"
  {
    type: "Inspection",
    sub: "claim",
    step: "exterior-rearscreen",
    overlayImage: "FrontFull.png",
    overlayImageSize: "50%",
    side: "REAR_SCREEN",
  },
];
